#!/usr/bin/env python3
"""Generate the 8-petal chord wheel as GB 2bpp tiles + map (11x11 tiles, 88x88 px)."""
import math

W = H = 88
CX = CY = 43.5
R_OUT = 42.0
R_IN = 15.0
TILE_BASE = 133  # after font-managed area and 5 D-pad tiles (128-132)

px = [[0] * W for _ in range(H)]

# circles (outer + inner) as outlines
for y in range(H):
    for x in range(W):
        d = math.hypot(x - CX, y - CY)
        if abs(d - R_OUT) <= 0.8 or abs(d - R_IN) <= 0.8:
            px[y][x] = 3

# 8 radial boundary lines at 22.5 + 45k degrees (0 = up)
for k in range(8):
    a = math.radians(22.5 + 45 * k)
    dx, dy = math.sin(a), -math.cos(a)
    t = R_IN
    while t <= R_OUT:
        x = int(round(CX + dx * t))
        y = int(round(CY + dy * t))
        if 0 <= x < W and 0 <= y < H:
            px[y][x] = 3
        t += 0.35

# tiles + dedupe
tiles = []
index = {}
tile_map = []
for ty in range(11):
    for tx in range(11):
        data = bytearray()
        for r in range(8):
            row = px[ty * 8 + r][tx * 8:(tx + 1) * 8]
            mask = 0
            for i, p in enumerate(row):
                if p:
                    mask |= 0x80 >> i
            data += bytes((mask, mask))  # color 3: both planes
        key = bytes(data)
        if key not in index:
            index[key] = len(tiles)
            tiles.append(key)
        tile_map.append(TILE_BASE + index[key])

n = len(tiles)
assert TILE_BASE + n <= 256, f"too many tiles: {n}"

with open("src/wheel_gfx.h", "w") as f:
    f.write("/* Generated by tools/gen_wheel.py - do not edit */\n")
    f.write("#ifndef WHEEL_GFX_H\n#define WHEEL_GFX_H\n#include <stdint.h>\n")
    f.write(f"#define WHEEL_TILE_BASE {TILE_BASE}\n")
    f.write(f"#define WHEEL_TILE_COUNT {n}\n")
    f.write("extern const uint8_t wheel_tiles[];\n")
    f.write("extern const uint8_t wheel_map[121];\n")
    f.write("#endif\n")

with open("src/wheel_gfx.c", "w") as f:
    f.write("/* Generated by tools/gen_wheel.py - do not edit */\n")
    f.write('#include "wheel_gfx.h"\n\n')
    f.write("const uint8_t wheel_tiles[] = {\n")
    for t in tiles:
        f.write("    " + ",".join(f"0x{b:02X}" for b in t) + ",\n")
    f.write("};\n\nconst uint8_t wheel_map[121] = {\n")
    for row in range(11):
        chunk = tile_map[row * 11:(row + 1) * 11]
        f.write("    " + ",".join(str(v) for v in chunk) + ",\n")
    f.write("};\n")

print(f"{n} unique tiles (VRAM {TILE_BASE}..{TILE_BASE + n - 1})")
