#!/usr/bin/env python3
"""Circled-digit badge tiles (1-7): filled disc, digit carved out in color 0."""
BASE = 206  # after wheel tiles 133-205

DISC = [
    "00111100",
    "01111110",
    "11111111",
    "11111111",
    "11111111",
    "11111111",
    "01111110",
    "00111100",
]
DIGITS = {  # 3x5, rows 1-5, cols 2-4
    1: ["010", "110", "010", "010", "111"],
    2: ["111", "001", "111", "100", "111"],
    3: ["111", "001", "011", "001", "111"],
    4: ["101", "101", "111", "001", "001"],
    5: ["111", "100", "111", "001", "111"],
    6: ["100", "100", "111", "101", "111"],
    7: ["111", "001", "001", "010", "010"],
}

out = []
for d in range(1, 8):
    for y in range(8):
        mask = 0
        for x in range(8):
            on = DISC[y][x] == "1"
            if 1 <= y <= 5 and 2 <= x <= 4 and DIGITS[d][y - 1][x - 2] == "1":
                on = False  # carve the digit
            if on:
                mask |= 0x80 >> x
        out += [mask, mask]

with open("src/badge_gfx.h", "w") as f:
    f.write("/* Generated by tools/gen_badges.py - do not edit */\n")
    f.write("#ifndef BADGE_GFX_H\n#define BADGE_GFX_H\n#include <stdint.h>\n")
    f.write(f"#define BADGE_TILE_BASE {BASE}\n#define BADGE_TILE_COUNT 7\n")
    f.write("extern const uint8_t badge_tiles[];\n#endif\n")

with open("src/badge_gfx.c", "w") as f:
    f.write("/* Generated by tools/gen_badges.py - do not edit */\n")
    f.write('#include "badge_gfx.h"\n\nconst uint8_t badge_tiles[] = {\n')
    for i in range(7):
        row = out[i * 16:(i + 1) * 16]
        f.write("    " + ",".join(f"0x{b:02X}" for b in row) + f", /* {i+1} */\n")
    f.write("};\n")
print("ok")
