/* Generated by scratchpad/gen_badges.py - do not edit */
#ifndef BADGE_GFX_H
#define BADGE_GFX_H
#include <stdint.h>
#define BADGE_TILE_BASE 206
#define BADGE_TILE_COUNT 7
extern const uint8_t badge_tiles[];
#endif
