/* Generated by tools/gen_wheel.py - do not edit */
#ifndef WHEEL_GFX_H
#define WHEEL_GFX_H
#include <stdint.h>
#define WHEEL_TILE_BASE 133
#define WHEEL_TILE_COUNT 73
extern const uint8_t wheel_tiles[];
extern const uint8_t wheel_map[121];
#endif
